### ISSUE TITLE
Error to auth delete with --ip for website or global.

### ISSUE THREAD

**Issue by petermann** [EasyEngine/easyengine#1463]
`ee auth delete global --ip=IP_ADDRESS`

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Auth_Command::clean_and_validate_ips() must be of the type string, null given, called in phar:///usr/local/bin/ee/vendor/easyengine/auth-command/src/Auth_Command.php on line 613 and defined in phar:///usr/local/bin/ee/vendor/easyengine/auth-command/src/Auth_Command.php:102
Stack trace:
#0 phar:///usr/local/bin/ee/vendor/easyengine/auth-command/src/Auth_Command.php(613): Auth_Command->clean_and_validate_ips(NULL)
#1 [internal function]: Auth_Command->delete(Array, Array)
#2 phar:///usr/local/bin/ee/php/EE/Dispatcher/CommandFactory.php(96): call_user_func(Array, Array, Array)
#3 [internal function]: EE\Dispatcher\CommandFactory::EE\Dispatcher\{closure}(Array, Array)
#4 phar:///usr/local/bin/ee/php/EE/Dispatcher/Subcommand.php(272): call_user_func(Object(Closure), Array, Array)
#5 phar:///usr/local/bin/ee/php/EE/Runner.php(338): EE\Dispatcher\Subcommand->invoke(Array, Array, Array)
#6 phar:///usr/local/bin/ee/php/EE/Runner.php(361): EE\Runner->run_command(Array, Array)
#7 in phar:///usr/local/bin/ee/vendor/easyengine/auth-command/src/Auth_Command.php on line 102
```

**Note:** I only view this error after upgrading to version 4.1.1.

[ee_info.txt](https://github.com/EasyEngine/easyengine/files/5015806/ee_info.txt)

Thanks!

**Comment by kirtangajjar** [comment]
Thanks @petermann for reporting this issue, we've fixed it and we will release it in v4.1.2 shortly.
