### ISSUE TITLE
SSL certificate fails to be renewed

### ISSUE THREAD

**Issue by lucasff** [EasyEngine/easyengine#1469]
Debug: Loading account keypair (33.751s)
Debug: Starting check with solver http (33.751s)
Debug: Loading the authorization token for domains [REDACTED], www.[REDACTED] ... (33.752s)
Debug: Challenge loaded. (33.752s)
Debug: Testing the challenge for domain [REDACTED] (36.953s)

Then in this step, it gets stuck for a long time.

Finally, I get a PHP Fatal:

PHP Fatal error:  Uncaught Exception: Can not validate challenge for domain [REDACTED] in phar:///usr/local/bin/ee/vendor/easyengine/site-command/src/helper/Site_Letsencrypt.php:387
Stack trace:
#0 phar:///usr/local/bin/ee/vendor/easyengine/site-command/src/helper/class-ee-site.php(1536): EE\Site\Type\Site_Letsencrypt->check(Array, '0', '')
#1 phar:///usr/local/bin/ee/vendor/easyengine/site-command/src/helper/class-ee-site.php(1422): EE\Site\Type\EE_Site_Command->ssl(Array, Array, true)
#2 phar:///usr/local/bin/ee/vendor/easyengine/site-command/src/helper/class-ee-site.php(1363): EE\Site\Type\EE_Site_Command->init_le('[REDACTED]', '/opt/easyengine...', '0', true, false, Array)
#3 phar:///usr/local/bin/ee/vendor/easyengine/site-command/src/helper/class-ee-site.php(1303): EE\Site\Type\EE_Site_Command->init_ssl('[REDACTED]', '/opt/easyengine...', 'le', '0', true, false, Array)
#4 phar:///usr/local/bin/ee/vendor/easyengine/site-command/src/helper/class-ee-site.php(1668): EE\Site\Type\EE_Site_Command->www_ssl_wrapper in phar:///usr/local/bin/ee/vendor/easyengine/site-command/src/helper/Site_Letsencrypt.php on line 387

What I'm noticing is that while the command is running, the website goes completely down. I think the proxy container is not behaving well, so the LE challenge doesn't complete properly.

```
+-------------------+---------------------------------------------------------------------------+
| OS                | Linux 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 |
| Shell             | /bin/bash                                                                 |
| PHP binary        | /usr/bin/php7.3                                                           |
| PHP version       | 7.3.18-1+ubuntu18.04.1+deb.sury.org+1                                     |
| php.ini used      | /etc/php/7.3/cli/php.ini                                                  |
| EE root dir       | phar://ee.phar                                                            |
| EE vendor dir     | phar://ee.phar/vendor                                                     |
| EE phar path      | /root                                                                     |
| EE packages dir   |                                                                           |
| EE global config  | /opt/easyengine/config/config.yml                                         |
| EE project config |                                                                           |
| EE version        | 4.1.3                                                                     |
+-------------------+---------------------------------------------------------------------------+
```

```
LSB Version:	core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

Docker version 19.03.9, build 9d988398e7
docker-compose version 1.25.5, build 8a1c60f6

- [x] ee cli info
- [x] lsb_release -a
- [x] docker version
- [x] docker-compose version

**Comment by rongchaua** [comment]
@lucasff Did you find out how to solve the problem? I have now the same problem but I have no idea how to solve it. I can't even turn off the SSL. :(

![image](https://user-images.githubusercontent.com/6661713/106389049-9e539000-63e1-11eb-97ea-389ec6990f27.png)
