### ISSUE TITLE
No such table: cron in phar:///usr/local/bin/ee/php/class-ee-db.php:115

### ISSUE THREAD

**Issue by joebailey26** [EasyEngine/easyengine#1500]
When I create a new site using:
`ee site create SITE_URL --type=wp --ssl=custom --ssl-key='/ssl-keys/KEY' --ssl-crt='/ssl-keys/CERTIFICATE' --php=7.4 --local-db
` 
I get an error message stating:
`No such table: cron in phar:///usr/local/bin/ee/php/class-ee-db.php:115
`
The site is still created successfully, it just doesn't output the success message and site details.

System Information
- [*] ee cli info
```
+-------------------+---------------------------------------------------------------------------+
| OS                | Linux 5.8.0-48-generic #54-Ubuntu SMP Fri Mar 19 14:25:20 UTC 2021 x86_64 |
| Shell             | /bin/bash                                                                 |
| PHP binary        | /usr/bin/php7.4                                                           |
| PHP version       | 7.4.12                                                                    |
| php.ini used      | /etc/php/7.4/cli/php.ini                                                  |
| EE root dir       | phar://ee.phar                                                            |
| EE vendor dir     | phar://ee.phar/vendor                                                     |
| EE phar path      | /root                                                                     |
| EE packages dir   |                                                                           |
| EE global config  | /opt/easyengine/config/config.yml                                         |
| EE project config |                                                                           |
| EE version        | 4.1.5                                                                     |
+-------------------+---------------------------------------------------------------------------+
```
- [*] lsb_release -a
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.10
Release:        20.10
Codename:       groovy
```
- [*] docker version
```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```
- [*] docker-compose version
```
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Comment by joebailey26** [comment]
Full error message:
```
Starting site creation.
Configuring project.
Creating WordPress site ******
Copying configuration files.
Starting site's services.
Downloading and configuring WordPress.
Moved /var/www/htdocs/wp-config.php to /var/www/wp-config.php successfully
Checking and verifying site-up status. This may take some time.

Installing WordPress site.
Success: ***** has been created successfully!
Starting site's services.
Site entry created.
Creating cron entry
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: cron in phar:///usr/local/bin/ee/php/class-ee-db.php:346
Stack trace:
#0 phar:///usr/local/bin/ee/php/class-ee-db.php(346): PDO->prepare()
#1 phar:///usr/local/bin/ee/php/EE/Model/Base.php(162): EE_DB->insert()
#2 phar:///usr/local/bin/ee/vendor/easyengine/cron-command/src/Cron_Command.php(121): EE\Model\Base::create()
#3 [internal function]: Cron_Command->create()
#4 phar:///usr/local/bin/ee/php/EE/Dispatcher/CommandFactory.php(96): call_user_func()
#5 [internal function]: EE\Dispatcher\CommandFactory::EE\Dispatcher\{closure}()
#6 phar:///usr/local/bin/ee/php/EE/Dispatcher/Subcommand.php(272): call_user_func()
#7 phar:///usr/local/bin/ee/php/EE/Runner.php(338): EE\Dispatcher\Subcommand->invoke()
#8 phar:///usr/local/bin/ee/php/EE/Runner.php(361): EE\Runner->run_command()
#9 phar:///usr/local/bin/ee/php/EE/Runner.php(788): EE\Runner->_run_command_and_exit()
#10 phar:///usr/local/bin/ee/php/EE/Bootstrap/LaunchRunner.php(23): EE\Runner->sta in phar:///usr/local/bin/ee/php/class-ee-db.php on line 346
```

**Comment by joebailey26** [comment]
Somehow the table cron had gotten deleted in the database. I re-added it by downloading the database file and opening it up. EE then went through and set all the values again.
