### ISSUE TITLE
[Bug] /ee-admin/pra/ throws 500 error

### ISSUE THREAD

**Issue by dhsathiya** [EasyEngine/easyengine#1705]
```
[10-Jun-2022 07:07:06] WARNING: [pool www] child 9 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught InvalidArgumentException: Invalid parameters URI: tcp://:6379 in /var/www/htdocs/ee-admin/pra/vendor/src/Connection/Parameters.php:93"
[10-Jun-2022 07:07:06] WARNING: [pool www] child 9 said into stderr: "Stack trace:"
[10-Jun-2022 07:07:06] WARNING: [pool www] child 9 said into stderr: "#0 /var/www/htdocs/ee-admin/pra/vendor/src/Connection/Factory.php(155): Predis\Connection\Parameters::parse('tcp://:6379')"
[10-Jun-2022 07:07:06] WARNING: [pool www] child 9 said into stderr: "#1 /var/www/htdocs/ee-admin/pra/vendor/src/Connection/Factory.php(84): Predis\Connection\Factory->createParameters('tcp://:6379')"
[10-Jun-2022 07:07:06] WARNING: [pool www] child 9 said into stderr: "#2 /var/www/htdocs/ee-admin/pra/vendor/src/Client.php(110): Predis\Connection\Factory->create('tcp://:6379')"
[10-Jun-2022 07:07:06] WARNING: [pool www] child 9 said into stderr: "#3 /var/www/htdocs/ee-admin/pra/vendor/src/Client.php(56): Predis\Client->createConnection('tcp://:6379')"
[10-Jun-2022 07:07:06] WARNING: [pool www] child 9 said into stderr: "#4 /var/www/htdocs/ee-admin/pra/includes/common.inc.php(118): Predis\Client->__construct('tcp://:6379')"
[10-Jun-2022 07:07:06] WARNING: [pool www] child 9 said into stderr: "#5 /var/www/htdocs/ee-admin/pra/index.php(3): require_once('/var/www/htdocs...')"
[10-Jun-2022 07:07:06] WARNING: [pool www] child 9 said into stderr: "#6 {main}"
[10-Jun-2022 07:07:06] WARNING: [pool www] child 9 said into stderr: "  thrown in /var/www/htdocs/ee-admin/pra/vendor/src/Connection/Parameters.php on line 93"
```

```
$ ee cli version
EE 4.5.6
```

**Comment by mrrobot47** [comment]
Unable to recreate the error. Can you please test this on a fresh site?

**Comment by mrrobot47** [comment]
Closing as this is not reproducable.
