### ISSUE TITLE
Unable to create site with Let's Encrypt SSL after upgrade to EE v4.6.0

### ISSUE THREAD

**Issue by arklid** [EasyEngine/easyengine#1722]
I recently updated to EE version 4.6.0 and are now getting the following error when trying to create a new site using Let's Encrypt SSL:

```
root@ee:~# ee site create [REDUCTED] --type=wp --locale=sv_SE --cache --ssl=le --le-mail=[REDUCTED]
Starting site creation.
Configuring project.
Creating WordPress site [REDUCTED]
Copying configuration files.
Starting site's services.
Downloading and configuring WordPress.
Moved /var/www/htdocs/wp-config.php to /var/www/wp-config.php successfully
Checking and verifying site-up status. This may take some time.

Installing WordPress site.
Success: https://[REDUCTED] has been created successfully!
PHP Fatal error:  Uncaught Error: Undefined constant "GuzzleHttp\IDNA_DEFAULT" in phar:///usr/local/bin/ee/vendor/guzzlehttp/guzzle/src/Client.php:218
Stack trace:
#0 phar:///usr/local/bin/ee/vendor/guzzlehttp/guzzle/src/Client.php(112): GuzzleHttp\Client->buildUri()
#1 phar:///usr/local/bin/ee/vendor/guzzlehttp/guzzle/src/Client.php(129): GuzzleHttp\Client->sendAsync()
#2 phar:///usr/local/bin/ee/vendor/acmephp/core/Http/SecureHttpClient.php(337): GuzzleHttp\Client->send()
#3 phar:///usr/local/bin/ee/vendor/acmephp/core/Http/SecureHttpClient.php(346): AcmePhp\Core\Http\SecureHttpClient->AcmePhp\Core\Http\{closure}()
#4 phar:///usr/local/bin/ee/vendor/acmephp/core/AcmeClient.php(312): AcmePhp\Core\Http\SecureHttpClient->request()
#5 phar:///usr/local/bin/ee/vendor/acmephp/core/AcmeClient.php(89): AcmePhp\Core\AcmeClient->getResourceUrl()
#6 phar:///usr/local/bin/ee/vendor/acmephp/core/AcmeClient.php(334): AcmePhp\Core\AcmeClient->getHttpClient()
#7 phar:///usr/local/bin/ee/vendor/acmephp/core/AcmeClient.php(112): AcmePhp\Core\AcmeClient->requestResource()
#8 phar:///usr/local/bin/ee/vendor/easyengine/site-command/src/helper/Site_Letsencrypt.php(179): AcmePhp\Core\AcmeClient->registerAccount()
#9 phar:///usr/local/bin/ee/vendor/easyengine/site-command/src/helper/class-ee-site.php(1504): EE\Site\Type\Site_Letsencrypt->register()
#10 phar:///usr/local/bin/ee/vendor/easyengine/site-command/src/helper/class-ee-site.php(1467): EE\Site\Type\EE_Site_Command->init_le()
#11 phar:///usr/local/bin/ee/vendor/easyengine/site-command/src/helper/class-ee-site.php(1406): EE\Site\Type\EE_Site_Command->init_ssl()
#12 phar:///usr/local/bin/ee/vendor/easyengine/site-type-wp/src/WordPress.php(1012): EE\Site\Type\EE_Site_Command->www_ssl_wrapper()
#13 phar:///usr/local/bin/ee/vendor/easyengine/site-type-wp/src/WordPress.php(437): EE\Site\Type\WordPress->create_site()
#14 [internal function]: EE\Site\Type\WordPress->create()
#15 phar:///usr/local/bin/ee/php/EE/Dispatcher/CommandFactory.php(96): call_user_func()
#16 [internal function]: EE\Dispatcher\CommandFactory::EE\Dispatcher\{closure}()
#17 phar:///usr/local/bin/ee/php/EE/Dispatcher/Subcommand.php(272): call_user_func()
#18 phar:///usr/local/bin/ee/php/EE/Runner.php(335): EE\Dispatcher\Subcommand->invoke()
#19 phar:///usr/local/bin/ee/php/class-ee.php(1184): EE\Runner->run_command()
#20 phar:///usr/local/bin/ee/vendor/easyengine/site-command/src/Site_Command.php(154): EE::run_command()
#21 [internal function]: Site_Command->__invoke()
#22 phar:///usr/local/bin/ee/php/EE/Dispatcher/CommandFactory.php(96): call_user_func()
#23 [internal function]: EE\Dispatcher\CommandFactory::EE\Dispatcher\{closure}()
#24 phar:///usr/local/bin/ee/php/EE/Dispatcher/Subcommand.php(272): call_user_func()
#25 phar:///usr/local/bin/ee/php/EE/Runner.php(335): EE\Dispatcher\Subcommand->invoke()
#26 phar:///usr/local/bin/ee/php/EE/Runner.php(358): EE\Runner->run_command()
#27 phar:///usr/local/bin/ee/php/EE/Runner.php(784): EE\Runner->_run_command_and_exit()
#28 phar:///usr/local/bin/ee/php/EE/Bootstrap/LaunchRunner.php(23): EE\Runner->start()
#29 phar:///usr/local/bin/ee/php/bootstrap.php(74): EE\Bootstrap\LaunchRunner->process()
#30 phar:///usr/local/bin/ee/php/init-ee.php(27): EE\bootstrap()
#31 phar:///usr/local/bin/ee/php/boot-phar.php(8): include('...')
#32 /usr/local/bin/ee(5): include('...')
#33 {main}
  thrown in phar:///usr/local/bin/ee/vendor/guzzlehttp/guzzle/src/Client.php on line 218
Warning: An Error occurred. Initiating clean-up.
Warning: Exiting gracefully after rolling back. This may take some time.
[[REDUCTED]] Docker Containers removed.
[[REDUCTED]] site root removed.
Success: Site [REDUCTED] deleted.
Success: Rollback complete. Exiting now.
```

System Information
- [X] ee cli info
```
+-------------------+----------------------------------------------------------------------------+
| OS                | Linux 5.4.0-124-generic #140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022 x86_64 |
| Shell             | /bin/bash                                                                  |
| PHP binary        | /usr/bin/php8.0                                                            |
| PHP version       | 8.0.21                                                                     |
| php.ini used      | /etc/php/8.0/cli/php.ini                                                   |
| EE root dir       | phar://ee.phar                                                             |
| EE vendor dir     | phar://ee.phar/vendor                                                      |
| EE phar path      | /root                                                                      |
| EE packages dir   |                                                                            |
| EE global config  | /opt/easyengine/config/config.yml                                          |
| EE project config |                                                                            |
| EE version        | 4.6.0                                                                      |
+-------------------+----------------------------------------------------------------------------+
```

- [X] lsb_release -a
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

- [X] docker version
```
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:57 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:03 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.7
  GitCommit:        0197261a30bf81f1ee8e6a4dd2dea0ef95d67ccb
 runc:
  Version:          1.1.3
  GitCommit:        v1.1.3-0-g6724737
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
- [X] docker-compose version
```
docker-compose version 1.29.2, build 5becea4c
docker-py version: 5.0.0
CPython version: 3.7.10
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Comment by afruit** [comment]
I also am stymied by this issue.

**Comment by adramm** [comment]
I have this issue as well.

**Comment by mrrobot47** [comment]
Thanks for submitting the issue.
I will be looking into this on priority.

**Comment by mrrobot47** [comment]
Fixed in [EE v4.6.2](https://github.com/EasyEngine/easyengine/releases/tag/v4.6.1). Update using `ee cli update` and try creating site with ssl.

**Comment by afruit** [comment]
Thank You, so much. 
I'm currently stuck on a client site that needs SSL.

Let me know how I can buy you a coffee, or beer, etc... 
**We appreciate Easy Engine.**

**Comment by arklid** [comment]
Confirmed fixed in stable EE v.4.6.1 on Ubuntu 20.04 and also Ubuntu 22.04
