### ISSUE TITLE
Broken Nginx Package

### ISSUE THREAD

**Issue by MiteshShah** [EasyEngine/easyengine#713]
Please attach the output of following command when open a new support request.
- [x] lsb_release -a
  No LSB modules are available.
  Distributor ID: Ubuntu
  Description:    Ubuntu 14.04.4 LTS
  Release:    14.04
  Codename:   trusty
- [x] ee -v
  EasyEngine v3.5.6
  Copyright (c) 2015 rtCamp Solutions Pvt. Ltd. 

```
016-05-16 08:07:51,206 (INFO) ee : Installing packages, please wait...
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nginx-custom : Depends: nginx-ee (= 1.10.0-1ppa) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
2016-05-16 08:07:51,708 (INFO) ee : Oops Something went wrong!!
2016-05-16 08:07:51,709 (ERROR) ee : Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!
2016-05-16 08:13:30,155 (DEBUG) ee : logging initialized for 'ee' using LoggingLogHandler
2016-05-16 08:13:30,422 (DEBUG) ee : ['/usr/local/bin/ee', '-v']
2016-05-16 08:13:30,423 (DEBUG) ee : collecting arguments/commands for <ee.cli.controllers.base.EEBaseController object at 0x7f5859e7c748>
2016-05-16 08:13:39,060 (DEBUG) ee : logging initialized for 'ee' using LoggingLogHandler
2016-05-16 08:13:39,311 (DEBUG) ee : ['/usr/local/bin/ee', 'info']
2016-05-16 08:13:39,311 (DEBUG) ee : collecting arguments/commands for <ee.cli.controllers.base.EEBaseController object at 0x7fd378d9a748>
2016-05-16 08:13:39,313 (DEBUG) ee : collecting arguments/commands for <ee.cli.plugins.info.EEInfoController object at 0x7fd378d9a9e8>
2016-05-16 08:13:39,315 (INFO) ee : Initializing EasyEngine Database
2016-05-16 08:13:41,472 (ERROR) ee : Nginx is not installed
```

**Comment by arush-sal** [comment]
@MiteshShah Sorry for the inconvenience, we are somewhere in middle of v3.6.0 release. As the nginx-common package has been renamed to nginx-ee in the latest release and therefore these problematic behavior are expected to arise. Your patience is greatly appreciated.

**Comment by arush-sal** [comment]
@MiteshShah Sorry for the inconvenience, we are somewhere in middle of v3.6.0 release. As the nginx-common package has been renamed to nginx-ee in the latest release and therefore these problematic behavior are expected to arise. Your patience is greatly appreciated.

**Comment by MiteshShah** [comment]
@arush-sal Thanks for the update.

**Comment by arush-sal** [comment]
@MiteshShah Please update EasyEngine, try again and let us know if the issue is fixed or not.

**Comment by MiteshShah** [comment]
@arush-sal @iam404 Fresh Ubuntu 16.04
ee stack install command fail with exit status 1

```
^_^[root@example.com:~]# ee stack install 
Adding repository for MySQL, please wait...
Adding repository for NGINX, please wait...
Adding repository for PHP, please wait...
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 982, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\ufffd' in position 363: ordinal not in range(128)
Call stack:
  File "/usr/local/bin/ee", line 9, in <module>
    load_entry_point('ee==3.6.0', 'console_scripts', 'ee')()
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.0-py3.5.egg/ee/cli/main.py", line 100, in main
    app.run()
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/core/foundation.py", line 694, in run
    self.controller._dispatch()
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/core/controller.py", line 455, in _dispatch
    return func()
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/core/controller.py", line 461, in _dispatch
    return func()
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.0-py3.5.egg/ee/cli/plugins/stack.py", line 2404, in install
    self.pre_pref(apt_packages)
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.0-py3.5.egg/ee/cli/plugins/stack.py", line 197, in pre_pref
    EERepo.add(self, ppa=EEVariables.ee_php_repo)
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.0-py3.5.egg/ee/core/apt_repo.py", line 51, in add
    .format(ppa_name=ppa))
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.0-py3.5.egg/ee/core/shellexec.py", line 33, in cmd_exec
    .format(cmd_stdout, cmd_stderr))
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.0-py3.5.egg/ee/core/logging.py", line 47, in debug
    self.app.log.debug(Log.HEADER + msg + Log.ENDC)
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/ext/ext_logging.py", line 307, in debug
    self.backend.debug(msg, **kwargs)
Message: '\x1b[95mCommand Output: , \nCommand Error: gpg: keyring `/tmp/tmpmo30pof9/secring.gpg\' created\ngpg: keyring `/tmp/tmpmo30pof9/pubring.gpg\' created\ngpg: requesting key E5267A6C from hkp server keyserver.ubuntu.com\ngpg: /tmp/tmpmo30pof9/trustdb.gpg: trustdb created\ngpg: key E5267A6C: public key "Launchpad PPA for Ond\\xc5\\x99ej Sur\ufffd" imported\ngpg: Total number processed: 1\ngpg:               imported: 1  (RSA: 1)\nException in thread Thread-1:\nTraceback (most recent call last):\n  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner\n    self.run()\n  File "/usr/lib/python3.5/threading.py", line 862, in run\n    self._target(*self._args, **self._kwargs)\n  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in addkey_func\n    func(**kwargs)\n  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 386, in add_key\n    return apsk.add_ppa_signing_key()\n  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 263, in add_ppa_signing_key\n    tmp_export_keyring, signing_key_fingerprint, tmp_keyring_dir):\n  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 212, in _verify_fingerprint\n    got_fingerprints = self._get_fingerprints(keyring, keyring_dir)\n  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 204, in _get_fingerprints\n    output = subprocess.check_output(cmd, universal_newlines=True)\n  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output\n    **kwargs).stdout\n  File "/usr/lib/python3.5/subprocess.py", line 695, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File "/usr/lib/python3.5/subprocess.py", line 1052, in communicate\n    stdout = self.stdout.read()\n  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode\n    return codecs.ascii_decode(input, self.errors)[0]\nUnicodeDecodeError: \'ascii\' codec can\'t decode byte 0xc5 in position 92: ordinal not in range(128)\n\n\x1b[0m'
Arguments: ()
Updating apt-cache, please wait...
Fixing missing GPG keys, please wait...
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 982, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\ufffd' in position 199: ordinal not in range(128)
Call stack:
  File "/usr/local/bin/ee", line 9, in <module>
    load_entry_point('ee==3.6.0', 'console_scripts', 'ee')()
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.0-py3.5.egg/ee/cli/main.py", line 100, in main
    app.run()
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/core/foundation.py", line 694, in run
    self.controller._dispatch()
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/core/controller.py", line 455, in _dispatch
    return func()
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/core/controller.py", line 461, in _dispatch
    return func()
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.0-py3.5.egg/ee/cli/plugins/stack.py", line 2408, in install
    EEAptGet.update(self)
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.0-py3.5.egg/ee/core/aptget.py", line 39, in update
    EERepo.add_key(self, key, keyserver="hkp://pgp.mit.edu")
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.0-py3.5.egg/ee/core/apt_repo.py", line 88, in add_key
    + " --recv-keys {key}".format(key=keyids))
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.0-py3.5.egg/ee/core/shellexec.py", line 33, in cmd_exec
    .format(cmd_stdout, cmd_stderr))
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.0-py3.5.egg/ee/core/logging.py", line 47, in debug
    self.app.log.debug(Log.HEADER + msg + Log.ENDC)
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/ext/ext_logging.py", line 307, in debug
    self.backend.debug(msg, **kwargs)
Message: '\x1b[95mCommand Output: , \nCommand Error: gpg: requesting key E5267A6C from hkp server pgp.mit.edu\ngpg: key E5267A6C: public key "Launchpad PPA for Ond\\xc5\\x99ej Sur\ufffd" imported\ngpg: Total number processed: 1\ngpg:               imported: 1  (RSA: 1)\n\x1b[0m'
Arguments: ()
Installing packages, please wait...
Downloading MySQLTuner           [Done]
Downloading WP-CLI               [Done]
Downloading phpMyAdmin           [Done]
Downloading Adminer              [Done]
Downloading phpMemcachedAdmin    [Done]
Downloading clean.php            [Done]
Downloading opcache.php          [Done]
Downloading Opgui                [Done]
Downloading OCP.php              [Done]
Downloading Webgrind             [Done]
Downloading pt-query-advisor     [Done]
Downloading Anemometer           [Done]
Reload : postfix   [OK]
Reload : nginx     [OK]
Restart : php5.6-fpm[OK]
Reload : mysql     [OK]
```
```
O_O[root@example.com:~]# echo $?
1
```

**Comment by janiosarmento** [comment]
I had a similar issue. In my case, the LC_* environment variables, relayed from my OS (in Portuguese) in a SSH session, broke the EE Python scripts.

I changed my system to English and the issues were gone.

**Comment by buzucan** [comment]
Same problem on me. I tried and on debian 7,8 and ubuntu 14.04.

**Comment by tinof** [comment]
Same problem on UpCloud, fresh 16.04 Ubuntu install, and while installing EasyEngine I get this:  

Adding repository for PHP, please wait...
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 982, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\ufffd' in position 363: ordinal not in range(128)

Can't use easyengine on UpCloud, it's a shame.

**Comment by rahul286** [comment]
We have updated our Nginx build today - https://easyengine.io/blog/easyengine-v3-8/ 
Please try that.

Please use http://community.rtcamp.com/c/easyengine for future support questions.
