### ISSUE TITLE
service nginx reload failed on Ubuntu 16.04

### ISSUE THREAD

**Issue by luandro** [EasyEngine/easyengine#728]
Easy Engine install correctly but when I try to create a wp site using `sudo ee site create --wp example.com` I get this:
```
Reload : nginx     [Failed]
Oops Something went wrong !!
Calling cleanup actions ...
Reload : nginx     [OK]
service nginx reload failed. check issues with `nginx -t` command.
Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!
```

 `tail /var/log/ee/ee.log` prints:
```
2016-06-05 09:30:35,152 (INFO) ee : service nginx reload failed. check issues with `nginx -t` command.
2016-06-05 09:30:35,152 (ERROR) ee : Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!
```
`nginx -t ` is ok and there's nothing at `/var/log/ee/ee.log`.

I've tried twice on fresh Digital Ocean 16.04 machines, I got same results.

**Comment by luandro** [comment]
Tried installing again on a fresh Ubuntu 16.04. And here's the complete error log:
 ```
root@Ubuntu-16:~# ee site create --wp example.com
Adding repository for MySQL, please wait...
Adding repository for NGINX, please wait...
Adding repository for PHP, please wait...
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 982, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\ufffd' in position 363: ordinal not in range(128)
Call stack:
  File "/usr/local/bin/ee", line 9, in <module>
    load_entry_point('ee==3.6.2', 'console_scripts', 'ee')()
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.2-py3.5.egg/ee/cli/main.py", line 100, in main
    app.run()
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/core/foundation.py", line 694, in run
    self.controller._dispatch()
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/core/controller.py", line 455, in _dispatch
    return func()
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/core/controller.py", line 455, in _dispatch
    return func()
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/core/controller.py", line 461, in _dispatch
    return func()
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.2-py3.5.egg/ee/cli/plugins/site.py", line 602, in default
    ee_auth = site_package_check(self, stype)
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.2-py3.5.egg/ee/cli/plugins/site_functions.py", line 954, in site_package_check
    disp_msg=False))
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.2-py3.5.egg/ee/cli/plugins/stack.py", line 2409, in install
    self.pre_pref(apt_packages)
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.2-py3.5.egg/ee/cli/plugins/stack.py", line 197, in pre_pref
    EERepo.add(self, ppa=EEVariables.ee_php_repo)
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.2-py3.5.egg/ee/core/apt_repo.py", line 51, in add
    .format(ppa_name=ppa))
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.2-py3.5.egg/ee/core/shellexec.py", line 33, in cmd_exec
    .format(cmd_stdout, cmd_stderr))
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.2-py3.5.egg/ee/core/logging.py", line 47, in debug
    self.app.log.debug(Log.HEADER + msg + Log.ENDC)
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/ext/ext_logging.py", line 307, in debug
    self.backend.debug(msg, **kwargs)
Message: '\x1b[95mCommand Output: , \nCommand Error: gpg: keyring `/tmp/tmp4qg4ya56/secring.gpg\' created\ngpg: keyring `/tmp/tmp4qg4ya56/pubring.gpg\' created\ngpg: requesting key E5267A6C from hkp server keyserver.ubuntu.com\ngpg: /tmp/tmp4qg4ya56/trustdb.gpg: trustdb created\ngpg: key E5267A6C: public key "Launchpad PPA for Ond\\xc5\\x99ej Sur\ufffd" imported\ngpg: Total number processed: 1\ngpg:               imported: 1  (RSA: 1)\nException in thread Thread-1:\nTraceback (most recent call last):\n  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner\n    self.run()\n  File "/usr/lib/python3.5/threading.py", line 862, in run\n    self._target(*self._args, **self._kwargs)\n  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in addkey_func\n    func(**kwargs)\n  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 386, in add_key\n    return apsk.add_ppa_signing_key()\n  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 263, in add_ppa_signing_key\n    tmp_export_keyring, signing_key_fingerprint, tmp_keyring_dir):\n  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 212, in _verify_fingerprint\n    got_fingerprints = self._get_fingerprints(keyring, keyring_dir)\n  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 204, in _get_fingerprints\n    output = subprocess.check_output(cmd, universal_newlines=True)\n  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output\n    **kwargs).stdout\n  File "/usr/lib/python3.5/subprocess.py", line 695, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File "/usr/lib/python3.5/subprocess.py", line 1052, in communicate\n    stdout = self.stdout.read()\n  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode\n    return codecs.ascii_decode(input, self.errors)[0]\nUnicodeDecodeError: \'ascii\' codec can\'t decode byte 0xc5 in position 92: ordinal not in range(128)\n\n\x1b[0m'
Arguments: ()
Adding SWAP file, please wait...
Fixing missing GPG keys, please wait...
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 982, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\ufffd' in position 199: ordinal not in range(128)
Call stack:
  File "/usr/local/bin/ee", line 9, in <module>
    load_entry_point('ee==3.6.2', 'console_scripts', 'ee')()
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.2-py3.5.egg/ee/cli/main.py", line 100, in main
    app.run()
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/core/foundation.py", line 694, in run
    self.controller._dispatch()
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/core/controller.py", line 455, in _dispatch
    return func()
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/core/controller.py", line 455, in _dispatch
    return func()
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/core/controller.py", line 461, in _dispatch
    return func()
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.2-py3.5.egg/ee/cli/plugins/site.py", line 602, in default
    ee_auth = site_package_check(self, stype)
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.2-py3.5.egg/ee/cli/plugins/site_functions.py", line 954, in site_package_check
    disp_msg=False))
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.2-py3.5.egg/ee/cli/plugins/stack.py", line 2411, in install
    EESwap.add(self)
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.2-py3.5.egg/ee/core/addswap.py", line 24, in add
    EEAptGet.update(self)
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.2-py3.5.egg/ee/core/aptget.py", line 39, in update
    EERepo.add_key(self, key, keyserver="hkp://pgp.mit.edu")
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.2-py3.5.egg/ee/core/apt_repo.py", line 88, in add_key
    + " --recv-keys {key}".format(key=keyids))
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.2-py3.5.egg/ee/core/shellexec.py", line 33, in cmd_exec
    .format(cmd_stdout, cmd_stderr))
  File "/usr/local/lib/python3.5/dist-packages/ee-3.6.2-py3.5.egg/ee/core/logging.py", line 47, in debug
    self.app.log.debug(Log.HEADER + msg + Log.ENDC)
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/ext/ext_logging.py", line 307, in debug
    self.backend.debug(msg, **kwargs)
Message: '\x1b[95mCommand Output: , \nCommand Error: gpg: requesting key E5267A6C from hkp server pgp.mit.edu\ngpg: key E5267A6C: public key "Launchpad PPA for Ond\\xc5\\x99ej Sur\ufffd" imported\ngpg: Total number processed: 1\ngpg:               imported: 1  (RSA: 1)\n\x1b[0m'
Arguments: ()
Updating apt-cache, please wait...
Installing packages, please wait...
Oops Something went wrong!!
Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!
```
where `tail /var/log/ee/ee.log` outputs:
```
Errors were encountered while processing:
 postfix
E: Sub-process /usr/bin/dpkg returned an error code (1)
2016-06-05 16:07:10,686 (INFO) ee : Oops Something went wrong!!
2016-06-05 16:07:10,689 (ERROR) ee : Check logs for reason `tail /var/log/ee/ee.log` & Try Again!!!
```

**Comment by w33zy** [comment]
Related tp #713

**Comment by Nikschavan** [comment]
Can you run `sudo service nginx reload`? what does it return?

**Comment by buzucan** [comment]
Same issue here. :(

**Comment by marcelomambembe** [comment]
Same issue here too. :(
