### ISSUE TITLE
can't run ee on debian stretch

### ISSUE THREAD

**Issue by jasonblewis** [EasyEngine/easyengine#838]
I installed ee on debian jessie, then upgraded to debian stretch (testint). now ee won't run.

Please attach the output of following command when open a new support request.

- [ ] lsb_release -a

No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.0 (stretch)
Release:	9.0
Codename:	stretch

- [ ] ee -v
Traceback (most recent call last):
  File "/usr/local/bin/ee", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ee==3.7.4' distribution was not found and is required by the application
- [ ] ee info
- [ ] wp --allow-root --info

Also unable to install it on debian testing: Executing apt-get update, please wait...
EasyEngine (ee) only support Ubuntu 12.04/14.04 and Debian 7.x/8.x

I realise that it's debian testing, however stretch is now in full freeze.

**Comment by MiteshShah** [comment]
@jasonblewis EasyEngine (ee) only support Ubuntu 12.04/14.04 and Debian 7.x/8.x

**Comment by jasonblewis** [comment]
@MiteshShah yes, I realise that. What I was trying to say is that supporting 9.x would be good as it's already in hard freeze and will be released soon (by some definition of soon)

**Comment by MiteshShah** [comment]
@jasonblewis Nice idea, I was misunderstood here :(

**Comment by mbtamuli** [comment]
Closing this issue for now. We'll soon release an update for supporting Debian 9.
