### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\ufffd' in position 199: ordinal not in range(128)

### ISSUE THREAD

**Issue by noogeu** [EasyEngine/easyengine#843]
After "ee site create example.com --wpfc" I get:

Adding repository for PHP, please wait...
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 982, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\ufffd' in position 363: ordinal not in range(128)
Call stack:
  File "/usr/local/bin/ee", line 9, in <module>
    load_entry_point('ee==3.7.4', 'console_scripts', 'ee')()
  File "/usr/local/lib/python3.5/dist-packages/ee-3.7.4-py3.5.egg/ee/cli/main.py", line 100, in main
    app.run()
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/core/foundation.py", line 694, in run
    self.controller._dispatch()
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/core/controller.py", line 455, in _dispatch
    return func()
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/core/controller.py", line 455, in _dispatch
    return func()
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/core/controller.py", line 461, in _dispatch
    return func()
  File "/usr/local/lib/python3.5/dist-packages/ee-3.7.4-py3.5.egg/ee/cli/plugins/site.py", line 598, in default
    ee_auth = site_package_check(self, stype)
  File "/usr/local/lib/python3.5/dist-packages/ee-3.7.4-py3.5.egg/ee/cli/plugins/site_functions.py", line 959, in site_package_check
    disp_msg=False))
  File "/usr/local/lib/python3.5/dist-packages/ee-3.7.4-py3.5.egg/ee/cli/plugins/stack.py", line 2443, in install
    self.pre_pref(apt_packages)
  File "/usr/local/lib/python3.5/dist-packages/ee-3.7.4-py3.5.egg/ee/cli/plugins/stack.py", line 191, in pre_pref
    EERepo.add(self, ppa=EEVariables.ee_php_repo)
  File "/usr/local/lib/python3.5/dist-packages/ee-3.7.4-py3.5.egg/ee/core/apt_repo.py", line 51, in add
    .format(ppa_name=ppa))
  File "/usr/local/lib/python3.5/dist-packages/ee-3.7.4-py3.5.egg/ee/core/shellexec.py", line 33, in cmd_exec
    .format(cmd_stdout, cmd_stderr))
  File "/usr/local/lib/python3.5/dist-packages/ee-3.7.4-py3.5.egg/ee/core/logging.py", line 47, in debug
    self.app.log.debug(Log.HEADER + msg + Log.ENDC)
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/ext/ext_logging.py", line 307, in debug
    self.backend.debug(msg, **kwargs)
Message: '\x1b[95mCommand Output: , \nCommand Error: gpg: keyring `/tmp/tmp2yd40ime/secring.gpg\' created\ngpg: keyring `/tmp/tmp2yd40ime/pubring.gpg\' created\ngpg: requesting key E5267A6C from hkp server keyserver.ubuntu.com\ngpg: /tmp/tmp2yd40ime/trustdb.gpg: trustdb created\ngpg: key E5267A6C: public key "Launchpad PPA for Ond\\xc5\\x99ej Sur\ufffd" imported\ngpg: Total number processed: 1\ngpg:               imported: 1  (RSA: 1)\nException in thread Thread-1:\nTraceback (most recent call last):\n  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner\n    self.run()\n  File "/usr/lib/python3.5/threading.py", line 862, in run\n    self._target(*self._args, **self._kwargs)\n  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in addkey_func\n    func(**kwargs)\n  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 401, in add_key\n    return apsk.add_ppa_signing_key()\n  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 271, in add_ppa_signing_key\n    tmp_export_keyring, signing_key_fingerprint, tmp_keyring_dir):\n  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 220, in _verify_fingerprint\n    got_fingerprints = self._get_fingerprints(keyring, keyring_dir)\n  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 212, in _get_fingerprints\n    output = subprocess.check_output(cmd, universal_newlines=True)\n  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output\n    **kwargs).stdout\n  File "/usr/lib/python3.5/subprocess.py", line 695, in run\n    stdout, stderr = process.communicate(input, timeout=timeout)\n  File "/usr/lib/python3.5/subprocess.py", line 1059, in communicate\n    stdout = self.stdout.read()\n  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode\n    return codecs.ascii_decode(input, self.errors)[0]\nUnicodeDecodeError: \'ascii\' codec can\'t decode byte 0xc5 in position 92: ordinal not in range(128)\n\n\x1b[0m'
Arguments: ()
Updating apt-cache, please wait...
Fixing missing GPG keys, please wait...
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 982, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\ufffd' in position 199: ordinal not in range(128)
Call stack:
  File "/usr/local/bin/ee", line 9, in <module>
    load_entry_point('ee==3.7.4', 'console_scripts', 'ee')()
  File "/usr/local/lib/python3.5/dist-packages/ee-3.7.4-py3.5.egg/ee/cli/main.py", line 100, in main
    app.run()
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/core/foundation.py", line 694, in run
    self.controller._dispatch()
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/core/controller.py", line 455, in _dispatch
    return func()
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/core/controller.py", line 455, in _dispatch
    return func()
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/core/controller.py", line 461, in _dispatch
    return func()
  File "/usr/local/lib/python3.5/dist-packages/ee-3.7.4-py3.5.egg/ee/cli/plugins/site.py", line 598, in default
    ee_auth = site_package_check(self, stype)
  File "/usr/local/lib/python3.5/dist-packages/ee-3.7.4-py3.5.egg/ee/cli/plugins/site_functions.py", line 959, in site_package_check
    disp_msg=False))
  File "/usr/local/lib/python3.5/dist-packages/ee-3.7.4-py3.5.egg/ee/cli/plugins/stack.py", line 2447, in install
    EEAptGet.update(self)
  File "/usr/local/lib/python3.5/dist-packages/ee-3.7.4-py3.5.egg/ee/core/aptget.py", line 39, in update
    EERepo.add_key(self, key, keyserver="hkp://pgp.mit.edu")
  File "/usr/local/lib/python3.5/dist-packages/ee-3.7.4-py3.5.egg/ee/core/apt_repo.py", line 88, in add_key
    + " --recv-keys {key}".format(key=keyids))
  File "/usr/local/lib/python3.5/dist-packages/ee-3.7.4-py3.5.egg/ee/core/shellexec.py", line 33, in cmd_exec
    .format(cmd_stdout, cmd_stderr))
  File "/usr/local/lib/python3.5/dist-packages/ee-3.7.4-py3.5.egg/ee/core/logging.py", line 47, in debug
    self.app.log.debug(Log.HEADER + msg + Log.ENDC)
  File "/usr/local/lib/python3.5/dist-packages/cement-2.4.0-py3.5.egg/cement/ext/ext_logging.py", line 307, in debug
    self.backend.debug(msg, **kwargs)
Message: '\x1b[95mCommand Output: , \nCommand Error: gpg: requesting key E5267A6C from hkp server pgp.mit.edu\ngpg: key E5267A6C: public key "Launchpad PPA for Ond\\xc5\\x99ej Sur\ufffd" imported\ngpg: Total number processed: 1\ngpg:               imported: 1  (RSA: 1)\n\x1b[0m'
Arguments: ()
Installing packages, please wait...

Please attach the output of following command when open a new support request.

# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial

# ee -v
EasyEngine v3.7.4
Copyright (c) 2016 rtCamp Solutions Pvt. Ltd.

# ee info

NGINX (1.10.0):

user                             www-data
worker_processes                 auto
worker_connections               4096
keepalive_timeout                30
fastcgi_read_timeout             300
client_max_body_size             100m
allow                            127.0.0.1 

PHP (5.6.30-1):

user                             
expose_php                       Off
memory_limit                     128M
post_max_size                    100M
upload_max_filesize              100M
max_execution_time               300

Information about www.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   off
listen                           127.0.0.1:9000

Information about debug.conf
ping.path                        /ping
pm.status_path                   /status
process_manager                  ondemand
pm.max_requests                  500
pm.max_children                  100
pm.start_servers                 20
pm.min_spare_servers             10
pm.max_spare_servers             30
request_terminate_timeout        300
xdebug.profiler_enable_trigger   on
listen                           127.0.0.1:9001
MySQL is not installed

# wp --allow-root --info
PHP binary:	/usr/bin/php5.6
PHP version:	5.6.30-1+deb.sury.org~xenial+1
php.ini used:	/etc/php/5.6/cli/php.ini
WP-CLI root dir:	phar://wp-cli.phar
WP-CLI packages dir:	
WP-CLI global config:	
WP-CLI project config:	
WP-CLI version:	0.24.1

**Comment by khromov** [comment]
Having the same issue on a newly installed Ubuntu 16.04 installation. It only seems to affect the logging though and not the functionality.

**Comment by benzon** [comment]
To be honest i think the development right now is a limbo, they are focusing on v4.

PhpMyAdmin is an old version that got a known bug with ENUM, and some other stuff.

And when you look ad the v4 it's hmm 29 days since last commit, so not sure where the heck the dev's has gone.

**Comment by manojchandrashekar** [comment]
This worked for me:

`sudo locale-gen en_US.UTF-8`
`export LANG=en_US.UTF-8`

From: http://askubuntu.com/questions/393638/unicodedecodeerror-ascii-codec-cant-decode-byte-0x-in-position-ordinal-n

**Comment by torpix** [comment]
@benzon 

I emailed them to see when v4 was planned for release and suggested a feature i would like and the reply i got was pretty much " We have ran out of funds and it's on hold "

**Comment by rahul286** [comment]
Thanks @manishsongirkar for the solution. It is what we do when we run into similar issues. Although it's not clear why the issue appears.

Regarding v4 - an update is posted here - https://easyengine.io/blog/easyengine-v4-status-update/
